
--repository_dependencies is the name of the table built from repository_dependencies CSV file from Libraries.io dataset
CREATE INDEX "repository_dependencies_dependency_project_name" ON repository_dependencies ("Dependency Project Name");

--Contains the list of all identified database dependencies
CREATE TABLE SQL_NOSQL_DEPENDENCY (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DBMS_TYPE VARCHAR2 NOT NULL,
    DBMS VARCHAR2 NOT NULL,
    DEPENDENCY_NAME VARCHAR2 NOT NULL,
    DEPENDENCY_LANGUAGE VARCHAR2 NOT NULL,
    ODM INTEGER(1) NOT NULL DEFAULT 0
);
--Contains the list of repositories and their underlying dependencies meta-data
CREATE TABLE SQL_NOSQL_REPOSITORY_DEPENDENCIES(
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    REPOSITORY_NAME VARCHAR2 NOT NULL,
    DEPENDENCY_MANIFEST_PLATFORM VARCHAR2 NOT NULL,
    DEPENDENCY_MANIFEST_FILE VARCHAR2 NOT NULL,
    DEPENDENCY_NAME VARCHAR2 NOT NULL,
    DEPENDENCY_ID INTEGER,
    DEPENDENCY_LANGUAGE VARCHAR2 NOT NULL,
    DBMS_TYPE VARCHAR2,
    DBMS VARCHAR2,
    ODM INTEGER(1) DEFAULT 0,
	DATASET_VERSION INTEGER NOT NULL
);
--Temporary table to build SQL_NOSQL_REPOSITORY_DEPENDENCIES table
CREATE TABLE TEMP_FILTERED_REPOSITORY_DEPENDENCIES (
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    REPOSITORY_NAME VARCHAR2 NOT NULL,
    DEPENDENCY_MANIFEST_PLATFORM VARCHAR2 NOT NULL,
    DEPENDENCY_MANIFEST_FILE VARCHAR2 NOT NULL,
    DEPENDENCY_NAME VARCHAR2 NOT NULL,
    DEPENDENCY_LANGUAGE VARCHAR2,
	DATASET_VERSION INTEGER NOT NULL
);

CREATE INDEX "SQL_NOSQL_REPOSITORY_DEPENDENCIES-REPOSITORY_NAME" ON SQL_NOSQL_REPOSITORY_DEPENDENCIES(REPOSITORY_NAME);
CREATE INDEX "SQL_NOSQL_REPOSITORY_DEPENDENCIES-DEPENDENCY_NAME" ON SQL_NOSQL_REPOSITORY_DEPENDENCIES(DEPENDENCY_NAME);
CREATE INDEX "SQL_NOSQL_REPOSITORY_DEPENDENCIES-DEPENDENCY_LANGUAGE" ON SQL_NOSQL_REPOSITORY_DEPENDENCIES(DEPENDENCY_LANGUAGE);
CREATE INDEX "SQL_NOSQL_REPOSITORY_DEPENDENCIES-DBMS_TYPE" ON SQL_NOSQL_REPOSITORY_DEPENDENCIES(DBMS_TYPE);
CREATE INDEX "SQL_NOSQL_REPOSITORY_DEPENDENCIES-DBMS" ON SQL_NOSQL_REPOSITORY_DEPENDENCIES(DBMS);
CREATE INDEX "SQL_NOSQL_REPOSITORY_DEPENDENCIES-ODM" ON SQL_NOSQL_REPOSITORY_DEPENDENCIES(ODM);
CREATE INDEX "SQL_NOSQL_REPOSITORY_DEPENDENCIES-DATASET_VERSION" ON SQL_NOSQL_REPOSITORY_DEPENDENCIES(DATASET_VERSION);

CREATE INDEX "FILTERED_REPOSITORY_DEPENDENCIES-DEPENDENCY_NAME" ON TEMP_FILTERED_REPOSITORY_DEPENDENCIES(DEPENDENCY_NAME);

--Contains all the versions of the list of repositories meta-data
CREATE TABLE SQL_NOSQL_DATASET_REPOSITORIES (
    DATASET_VERSION INTEGER not null,
    REPOSITORY_NAME VARCHAR2 not null,
	REPOSITORY_LANGUAGE VARCHAR2,
	HOST_TYPE VARCHAR2,
	DESCRIPTION VARCHAR2,
	STATUS VARCHAR2,
	FORK VARCHAR2,
	CREATION_DATETIME DATETIME,
	LAST_UPDATE_DATETIME DATETIME,
	LAST_PUSH_DATETIME DATETIME,
	LAST_SYNC_DATETIME DATETIME,
	HOMEPAGE_URL VARCHAR2,
	SIZE INTEGER,
	STARS_COUNT INTEGER,
	FORKS_COUNT INTEGER,
	OPEN_ISSUES_COUNT INTEGER,
	WATCHERS_COUNT INTEGER,
	CONTRIBUTORS_COUNT INTEGER,
	SOURCE_RANK INTEGER,
	SOURCE_FORK_REPOSITORY_NAME VARCHAR2,
	LICENCE VARCHAR2,
	KEYWORDS VARCHAR2
);
CREATE INDEX "SQL_NOSQL_DATASET_REPOSITORIES-REPOSITORY_NAME" ON SQL_NOSQL_DATASET_REPOSITORIES(REPOSITORY_NAME);
CREATE INDEX "SQL_NOSQL_DATASET_REPOSITORIES-DATASET_VERSION" ON SQL_NOSQL_DATASET_REPOSITORIES(DATASET_VERSION);

--Contains all the database-dependent repositories and flags for each DBMS
CREATE TABLE SQL_NOSQL_REPOSITORY_WITH_DBMS (
	REPOSITORY_NAME VARCHAR2 not null,
	HAS_POSTGRESQL_DEPENDENCY boolean default false,
	HAS_SQLITE_DEPENDENCY boolean default false,
	HAS_MYSQL_DEPENDENCY boolean default false,
	HAS_MONGO_DEPENDENCY boolean default false,
	HAS_COUCHBASE_DEPENDENCY boolean default false,
	HAS_REDIS_DEPENDENCY boolean default false,
	HAS_MEMCACHED_DEPENDENCY boolean default false,
	HAS_CASSANDRA_DEPENDENCY boolean default false,
	HAS_HBASE_DEPENDENCY boolean default false,
	HAS_NEO4J_DEPENDENCY boolean default false
);
CREATE INDEX 'SQL_NOSQL_REPOSITORY_WITH_DBMS-REPOSITORY_NAME' ON SQL_NOSQL_REPOSITORY_WITH_DBMS(REPOSITORY_NAME);

--Contains all the database-dependent repositories and flags for each data model
CREATE VIEW SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE(REPOSITORY_NAME, HAS_RELATIONAL_DB_DEPENDENCY, HAS_DOCUMENT_DB_DEPENDENCY, HAS_KEY_VALUE_DB_DEPENDENCY, HAS_COLUMN_DB_DEPENDENCY, HAS_GRAPH_DB_DEPENDENCY) AS
    SELECT REPOSITORY_NAME,
           CASE WHEN (HAS_MYSQL_DEPENDENCY = true OR HAS_SQLITE_DEPENDENCY = true OR HAS_POSTGRESQL_DEPENDENCY = true) THEN true ELSE false END,
           CASE WHEN (HAS_MONGO_DEPENDENCY = true OR HAS_COUCHBASE_DEPENDENCY = true) THEN true ELSE false END,
           CASE WHEN (HAS_REDIS_DEPENDENCY = true OR HAS_MEMCACHED_DEPENDENCY = true) THEN true ELSE false END,
           CASE WHEN (HAS_CASSANDRA_DEPENDENCY = true OR HAS_HBASE_DEPENDENCY = true) THEN true ELSE false END,
           CASE WHEN (HAS_NEO4J_DEPENDENCY = true) THEN true ELSE false END
	FROM SQL_NOSQL_REPOSITORY_WITH_DBMS;

