INSERT INTO SQL_NOSQL_REPOSITORY_WITH_DBMS(REPOSITORY_NAME)
SELECT DISTINCT REPOSITORY_NAME FROM SQL_NOSQL_REPOSITORY_DEPENDENCIES;

UPDATE SQL_NOSQL_REPOSITORY_WITH_DBMS SET HAS_POSTGRESQL_DEPENDENCY = true WHERE REPOSITORY_NAME in (SELECT DISTINCT REPOSITORY_NAME FROM SQL_NOSQL_REPOSITORY_DEPENDENCIES WHERE DBMS = 'PostgreSQL');
UPDATE SQL_NOSQL_REPOSITORY_WITH_DBMS SET HAS_SQLITE_DEPENDENCY = true WHERE REPOSITORY_NAME in (SELECT DISTINCT REPOSITORY_NAME FROM SQL_NOSQL_REPOSITORY_DEPENDENCIES WHERE DBMS = 'SQLite');
UPDATE SQL_NOSQL_REPOSITORY_WITH_DBMS SET HAS_MYSQL_DEPENDENCY = true WHERE REPOSITORY_NAME in (SELECT DISTINCT REPOSITORY_NAME FROM SQL_NOSQL_REPOSITORY_DEPENDENCIES WHERE DBMS = 'MySQL');
UPDATE SQL_NOSQL_REPOSITORY_WITH_DBMS SET HAS_MONGO_DEPENDENCY = true WHERE REPOSITORY_NAME in (SELECT DISTINCT REPOSITORY_NAME FROM SQL_NOSQL_REPOSITORY_DEPENDENCIES WHERE DBMS = 'MongoDB');
UPDATE SQL_NOSQL_REPOSITORY_WITH_DBMS SET HAS_COUCHBASE_DEPENDENCY = true WHERE REPOSITORY_NAME in (SELECT DISTINCT REPOSITORY_NAME FROM SQL_NOSQL_REPOSITORY_DEPENDENCIES WHERE DBMS = 'Couchbase');
UPDATE SQL_NOSQL_REPOSITORY_WITH_DBMS SET HAS_REDIS_DEPENDENCY = true WHERE REPOSITORY_NAME in (SELECT DISTINCT REPOSITORY_NAME FROM SQL_NOSQL_REPOSITORY_DEPENDENCIES WHERE DBMS = 'Redis');
UPDATE SQL_NOSQL_REPOSITORY_WITH_DBMS SET HAS_MEMCACHED_DEPENDENCY = true WHERE REPOSITORY_NAME in (SELECT DISTINCT REPOSITORY_NAME FROM SQL_NOSQL_REPOSITORY_DEPENDENCIES WHERE DBMS = 'Memcached');
UPDATE SQL_NOSQL_REPOSITORY_WITH_DBMS SET HAS_CASSANDRA_DEPENDENCY = true WHERE REPOSITORY_NAME in (SELECT DISTINCT REPOSITORY_NAME FROM SQL_NOSQL_REPOSITORY_DEPENDENCIES WHERE DBMS = 'Cassandra');
UPDATE SQL_NOSQL_REPOSITORY_WITH_DBMS SET HAS_HBASE_DEPENDENCY = true WHERE REPOSITORY_NAME in (SELECT DISTINCT REPOSITORY_NAME FROM SQL_NOSQL_REPOSITORY_DEPENDENCIES WHERE DBMS = 'HBase');
UPDATE SQL_NOSQL_REPOSITORY_WITH_DBMS SET HAS_NEO4J_DEPENDENCY = true WHERE REPOSITORY_NAME in (SELECT DISTINCT REPOSITORY_NAME FROM SQL_NOSQL_REPOSITORY_DEPENDENCIES WHERE DBMS = 'Neo4j');