
--Quality filtered repositories
CREATE VIEW FILTERED_REPOSITORIES_VIEW AS
    SELECT DISTINCT REPOSITORY_NAME
    FROM SQL_NOSQL_DATASET_REPOSITORIES
    WHERE LAST_PUSH_DATETIME IS NOT NULL
    AND CREATION_DATETIME IS NOT NULL
    AND LAST_PUSH_DATETIME > CREATION_DATETIME
    AND SIZE >= 100
    AND CONTRIBUTORS_COUNT >= 2
    AND STARS_COUNT >= 2
;

CREATE TABLE FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES (
	ID INTEGER,
	REPOSITORY_NAME VARCHAR2 not null,
	DEPENDENCY_MANIFEST_PLATFORM VARCHAR2 not null,
	DEPENDENCY_MANIFEST_FILE VARCHAR2 not null,
	DEPENDENCY_NAME VARCHAR2 not null,
	DEPENDENCY_ID INTEGER,
	DEPENDENCY_LANGUAGE VARCHAR2 not null,
	DBMS_TYPE VARCHAR2,
	DBMS VARCHAR2,
	ODM INTEGER(1) default 0,
	DATASET_VERSION INTEGER not null
);


create index "FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES-DATASET_VERSION" on FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES (DATASET_VERSION);
create index "FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES-DBMS" on FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES (DBMS);
create index "FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES-DBMS_TYPE" on FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES (DBMS_TYPE);
create index "FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES-DEPENDENCY_LANGUAGE" on FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES (DEPENDENCY_LANGUAGE);
create index "FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES-DEPENDENCY_NAME" on FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES (DEPENDENCY_NAME);
create index "FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES-ODM" on FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES (ODM);
create index "FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES-REPOSITORY_NAME" on FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES (REPOSITORY_NAME);

INSERT INTO FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES
SELECT * FROM SQL_NOSQL_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME FROM FILTERED_REPOSITORIES_VIEW
);
