create table SQL_NOSQL_FILTERED_NO_FORK_REPOSITORY_DEPENDENCIES
(
	ID INTEGER,
	REPOSITORY_NAME VARCHAR2 not null,
	DEPENDENCY_MANIFEST_PLATFORM VARCHAR2 not null,
	DEPENDENCY_MANIFEST_FILE VARCHAR2 not null,
	DEPENDENCY_NAME VARCHAR2 not null,
	DEPENDENCY_ID INTEGER,
	DEPENDENCY_LANGUAGE VARCHAR2 not null,
	DBMS_TYPE VARCHAR2,
	DBMS VARCHAR2,
	ODM INTEGER(1) default 0,
	DATASET_VERSION INTEGER not null,
	ID_TECH INTEGER not null
		constraint NOSQL_REPOSITORY_DEPENDENCIES_pk
			primary key autoincrement
);

create index "SQL_NOSQL_FILTERED_NO_FORK_REPOSITORY_DEPENDENCIES-DATASET_VERSION"
	on SQL_NOSQL_FILTERED_NO_FORK_REPOSITORY_DEPENDENCIES (DATASET_VERSION);

create index "SQL_NOSQL_FILTERED_NO_FORK_REPOSITORY_DEPENDENCIES-DBMS"
	on SQL_NOSQL_FILTERED_NO_FORK_REPOSITORY_DEPENDENCIES (DBMS);

create index "SQL_NOSQL_FILTERED_NO_FORK_REPOSITORY_DEPENDENCIES-DBMS_TYPE"
	on SQL_NOSQL_FILTERED_NO_FORK_REPOSITORY_DEPENDENCIES (DBMS_TYPE);

create index "SQL_NOSQL_FILTERED_NO_FORK_REPOSITORY_DEPENDENCIES-NOSQL_DEPENDENCY_LANGUAGE"
	on SQL_NOSQL_FILTERED_NO_FORK_REPOSITORY_DEPENDENCIES (DEPENDENCY_LANGUAGE);

create index "SQL_NOSQL_FILTERED_NO_FORK_REPOSITORY_DEPENDENCIES-NOSQL_DEPENDENCY_NAME"
	on SQL_NOSQL_FILTERED_NO_FORK_REPOSITORY_DEPENDENCIES (DEPENDENCY_NAME);

create index "SQL_NOSQL_FILTERED_NO_FORK_REPOSITORY_DEPENDENCIES-ODM"
	on SQL_NOSQL_FILTERED_NO_FORK_REPOSITORY_DEPENDENCIES (ODM);

create index "SQL_NOSQL_FILTERED_NO_FORK_REPOSITORY_DEPENDENCIES-REPOSITORY_NAME"
	on SQL_NOSQL_FILTERED_NO_FORK_REPOSITORY_DEPENDENCIES (REPOSITORY_NAME);


INSERT INTO SQL_NOSQL_FILTERED_NO_FORK_REPOSITORY_DEPENDENCIES
SELECT * FROM SQL_NOSQL_FILTERED_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (SELECT REPOSITORY_NAME FROM SQL_NOSQL_DATASET_REPOSITORIES WHERE FORK <> "true");