
--Quality filtered repositories
CREATE VIEW FILTERED_REPOSITORIES_VIEW AS
    SELECT DISTINCT REPOSITORY_NAME
    FROM SQL_NOSQL_DATASET_REPOSITORIES
    WHERE LAST_PUSH_DATETIME IS NOT NULL
    AND CREATION_DATETIME IS NOT NULL
    AND LAST_PUSH_DATETIME > CREATION_DATETIME
    AND SIZE >= 100
    AND CONTRIBUTORS_COUNT >= 2
    AND STARS_COUNT >= 2
;

CREATE TABLE FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES (
	ID INTEGER,
	REPOSITORY_NAME VARCHAR2 not null,
	DEPENDENCY_MANIFEST_PLATFORM VARCHAR2 not null,
	DEPENDENCY_MANIFEST_FILE VARCHAR2 not null,
	DEPENDENCY_NAME VARCHAR2 not null,
	DEPENDENCY_ID INTEGER,
	DEPENDENCY_LANGUAGE VARCHAR2 not null,
	DBMS_TYPE VARCHAR2,
	DBMS VARCHAR2,
	ODM INTEGER(1) default 0,
	DATASET_VERSION INTEGER not null
);


create index "FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES-DATASET_VERSION" on FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES (DATASET_VERSION);
create index "FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES-DBMS" on FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES (DBMS);
create index "FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES-DBMS_TYPE" on FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES (DBMS_TYPE);
create index "FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES-DEPENDENCY_LANGUAGE" on FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES (DEPENDENCY_LANGUAGE);
create index "FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES-DEPENDENCY_NAME" on FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES (DEPENDENCY_NAME);
create index "FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES-ODM" on FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES (ODM);
create index "FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES-REPOSITORY_NAME" on FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES (REPOSITORY_NAME);

INSERT INTO FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES
SELECT * FROM SQL_NOSQL_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME FROM FILTERED_REPOSITORIES_VIEW
);

-- Create tables without duplicated repositories
create table SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES as select REPOSITORY_NAME, DEPENDENCY_NAME, DEPENDENCY_NAME, DEPENDENCY_LANGUAGE, DATASET_VERSION, DBMS, DBMS_TYPE, ODM from SQL_NOSQL_REPOSITORY_DEPENDENCIES group by REPOSITORY_NAME, DEPENDENCY_NAME, DEPENDENCY_NAME, DEPENDENCY_LANGUAGE, DATASET_VERSION, DBMS, DBMS_TYPE, ODM;
create table SQL_NOSQL_DISTINCT_FILTERED_REPOSITORY_DEPENDENCIES as select REPOSITORY_NAME, DEPENDENCY_NAME, DEPENDENCY_NAME, DEPENDENCY_LANGUAGE, DATASET_VERSION, DBMS, DBMS_TYPE, ODM from FILTERED_SQL_NOSQL_REPOSITORY_DEPENDENCIES group by REPOSITORY_NAME, DEPENDENCY_NAME, DEPENDENCY_NAME, DEPENDENCY_LANGUAGE, DATASET_VERSION, DBMS, DBMS_TYPE, ODM;



-- Global numbers for database dependent projects
-- Column #projects with a database dependency
select count(distinct REPOSITORY_NAME), DATASET_VERSION from SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES group by DATASET_VERSION;
-- Column #projects with a Relational DB dependency
select count(distinct REPOSITORY_NAME), DATASET_VERSION from SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES where DBMS_TYPE='RelationalDB' group by DATASET_VERSION;
-- Column #projects with a NoSQL DB dependency
select count(distinct REPOSITORY_NAME), DATASET_VERSION from SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES where DBMS_TYPE<>'RelationalDB' group by DATASET_VERSION;

-- Number of project in 2020 having a dependency to specific DB technology. (r) is relational db, (d) document db, (k) key value, (c) column based, (g) graph # proj by DBMS
--select DATASET_VERSION, DBMS, count(distinct REPOSITORY_NAME) from SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES group by DATASET_VERSION, DBMS;
select DBMS, count(distinct REPOSITORY_NAME) from SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES where DATASET_VERSION='20200112' group by DBMS;

-- Number of projects in 2020 by database dependency programming language
--select DATASET_VERSION, DEPENDENCY_LANGUAGE, count(distinct(REPOSITORY_NAME)) from SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES group by DATASET_VERSION, DEPENDENCY_LANGUAGE;
select DEPENDENCY_LANGUAGE, count(distinct(REPOSITORY_NAME)) from SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES where DATASET_VERSION = '20200112' group by DEPENDENCY_LANGUAGE;

-- Number of projects in 2020 by dependency name and dependency programming language
--select DATASET_VERSION, DEPENDENCY_NAME, DEPENDENCY_LANGUAGE, ODM, count(distinct REPOSITORY_NAME) from SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES group by DATASET_VERSION, DEPENDENCY_NAME, DEPENDENCY_LANGUAGE;
select DEPENDENCY_NAME, DEPENDENCY_LANGUAGE, ODM, count(distinct REPOSITORY_NAME) from SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES where DATASET_VERSION='20200112' group by DEPENDENCY_NAME, DEPENDENCY_LANGUAGE;

--Number of projects having one database type
--Only relational DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = true
    AND HAS_DOCUMENT_DB_DEPENDENCY = false
    AND HAS_KEY_VALUE_DB_DEPENDENCY = false
    AND HAS_COLUMN_DB_DEPENDENCY = false
    AND HAS_GRAPH_DB_DEPENDENCY = false
) GROUP BY DATASET_VERSION;
--Only document DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = false
    AND HAS_DOCUMENT_DB_DEPENDENCY = true
    AND HAS_KEY_VALUE_DB_DEPENDENCY = false
    AND HAS_COLUMN_DB_DEPENDENCY = false
    AND HAS_GRAPH_DB_DEPENDENCY = false
) GROUP BY DATASET_VERSION;
--Only key-value DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = false
    AND HAS_DOCUMENT_DB_DEPENDENCY = false
    AND HAS_KEY_VALUE_DB_DEPENDENCY = true
    AND HAS_COLUMN_DB_DEPENDENCY = false
    AND HAS_GRAPH_DB_DEPENDENCY = false
) GROUP BY DATASET_VERSION;
--Only column DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = false
    AND HAS_DOCUMENT_DB_DEPENDENCY = false
    AND HAS_KEY_VALUE_DB_DEPENDENCY = false
    AND HAS_COLUMN_DB_DEPENDENCY = true
    AND HAS_GRAPH_DB_DEPENDENCY = false
) GROUP BY DATASET_VERSION;
--Only graph DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = false
    AND HAS_DOCUMENT_DB_DEPENDENCY = false
    AND HAS_KEY_VALUE_DB_DEPENDENCY = false
    AND HAS_COLUMN_DB_DEPENDENCY = false
    AND HAS_GRAPH_DB_DEPENDENCY = true
) GROUP BY DATASET_VERSION;

--Number of projects having two database types
--Relational DB & Key-Value DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = true
    AND HAS_DOCUMENT_DB_DEPENDENCY = false
    AND HAS_KEY_VALUE_DB_DEPENDENCY = true
    AND HAS_COLUMN_DB_DEPENDENCY = false
    AND HAS_GRAPH_DB_DEPENDENCY = false
) GROUP BY DATASET_VERSION;
--Relational DB & Document DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = true
    AND HAS_DOCUMENT_DB_DEPENDENCY = true
    AND HAS_KEY_VALUE_DB_DEPENDENCY = false
    AND HAS_COLUMN_DB_DEPENDENCY = false
    AND HAS_GRAPH_DB_DEPENDENCY = false
) GROUP BY DATASET_VERSION;
--Document DB & Key-Value DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = false
    AND HAS_DOCUMENT_DB_DEPENDENCY = true
    AND HAS_KEY_VALUE_DB_DEPENDENCY = true
    AND HAS_COLUMN_DB_DEPENDENCY = false
    AND HAS_GRAPH_DB_DEPENDENCY = false
) GROUP BY DATASET_VERSION;
--Relational DB & Column DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = true
    AND HAS_DOCUMENT_DB_DEPENDENCY = false
    AND HAS_KEY_VALUE_DB_DEPENDENCY = false
    AND HAS_COLUMN_DB_DEPENDENCY = true
    AND HAS_GRAPH_DB_DEPENDENCY = false
) GROUP BY DATASET_VERSION;
--Key-Value DB & Column DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = false
    AND HAS_DOCUMENT_DB_DEPENDENCY = false
    AND HAS_KEY_VALUE_DB_DEPENDENCY = true
    AND HAS_COLUMN_DB_DEPENDENCY = true
    AND HAS_GRAPH_DB_DEPENDENCY = false
) GROUP BY DATASET_VERSION;
--Document DB & Column DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = false
    AND HAS_DOCUMENT_DB_DEPENDENCY = true
    AND HAS_KEY_VALUE_DB_DEPENDENCY = false
    AND HAS_COLUMN_DB_DEPENDENCY = true
    AND HAS_GRAPH_DB_DEPENDENCY = false
) GROUP BY DATASET_VERSION;
--Relational DB & Graph DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = true
    AND HAS_DOCUMENT_DB_DEPENDENCY = false
    AND HAS_KEY_VALUE_DB_DEPENDENCY = false
    AND HAS_COLUMN_DB_DEPENDENCY = false
    AND HAS_GRAPH_DB_DEPENDENCY = true
) GROUP BY DATASET_VERSION;
--Document DB & Graph DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = false
    AND HAS_DOCUMENT_DB_DEPENDENCY = true
    AND HAS_KEY_VALUE_DB_DEPENDENCY = false
    AND HAS_COLUMN_DB_DEPENDENCY = false
    AND HAS_GRAPH_DB_DEPENDENCY = true
) GROUP BY DATASET_VERSION;
--Key-Value & Graph DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = false
    AND HAS_DOCUMENT_DB_DEPENDENCY = false
    AND HAS_KEY_VALUE_DB_DEPENDENCY = true
    AND HAS_COLUMN_DB_DEPENDENCY = false
    AND HAS_GRAPH_DB_DEPENDENCY = true
) GROUP BY DATASET_VERSION;
--Column DB & Graph DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = false
    AND HAS_DOCUMENT_DB_DEPENDENCY = false
    AND HAS_KEY_VALUE_DB_DEPENDENCY = false
    AND HAS_COLUMN_DB_DEPENDENCY = true
    AND HAS_GRAPH_DB_DEPENDENCY = true
) GROUP BY DATASET_VERSION;

--Number of projects having three database types
--Relational DB & Document DB & Key-Value DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = true
    AND HAS_DOCUMENT_DB_DEPENDENCY = true
    AND HAS_KEY_VALUE_DB_DEPENDENCY = true
    AND HAS_COLUMN_DB_DEPENDENCY = false
    AND HAS_GRAPH_DB_DEPENDENCY = false
) GROUP BY DATASET_VERSION;
--Relational DB & Key-Value DB & Column DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = true
    AND HAS_DOCUMENT_DB_DEPENDENCY = false
    AND HAS_KEY_VALUE_DB_DEPENDENCY = true
    AND HAS_COLUMN_DB_DEPENDENCY = true
    AND HAS_GRAPH_DB_DEPENDENCY = false
) GROUP BY DATASET_VERSION;
--Relational DB & Document DB & Column DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = true
    AND HAS_DOCUMENT_DB_DEPENDENCY = true
    AND HAS_KEY_VALUE_DB_DEPENDENCY = false
    AND HAS_COLUMN_DB_DEPENDENCY = true
    AND HAS_GRAPH_DB_DEPENDENCY = false
) GROUP BY DATASET_VERSION;
--Document DB & Key-Value DB & Column DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = false
    AND HAS_DOCUMENT_DB_DEPENDENCY = true
    AND HAS_KEY_VALUE_DB_DEPENDENCY = true
    AND HAS_COLUMN_DB_DEPENDENCY = true
    AND HAS_GRAPH_DB_DEPENDENCY = false
) GROUP BY DATASET_VERSION;
--Relational DB & Document DB & Graph DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = true
    AND HAS_DOCUMENT_DB_DEPENDENCY = true
    AND HAS_KEY_VALUE_DB_DEPENDENCY = false
    AND HAS_COLUMN_DB_DEPENDENCY = false
    AND HAS_GRAPH_DB_DEPENDENCY = true
) GROUP BY DATASET_VERSION;
--Document DB & Key-Value DB & Graph DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = false
    AND HAS_DOCUMENT_DB_DEPENDENCY = true
    AND HAS_KEY_VALUE_DB_DEPENDENCY = true
    AND HAS_COLUMN_DB_DEPENDENCY = false
    AND HAS_GRAPH_DB_DEPENDENCY = true
) GROUP BY DATASET_VERSION;
--Relational DB & Key-Value DB & Graph DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = true
    AND HAS_DOCUMENT_DB_DEPENDENCY = false
    AND HAS_KEY_VALUE_DB_DEPENDENCY = true
    AND HAS_COLUMN_DB_DEPENDENCY = false
    AND HAS_GRAPH_DB_DEPENDENCY = true
) GROUP BY DATASET_VERSION;
--Relational DB & Column DB & Graph DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = true
    AND HAS_DOCUMENT_DB_DEPENDENCY = false
    AND HAS_KEY_VALUE_DB_DEPENDENCY = false
    AND HAS_COLUMN_DB_DEPENDENCY = true
    AND HAS_GRAPH_DB_DEPENDENCY = true
) GROUP BY DATASET_VERSION;
--Document DB & Column DB & Graph DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = false
    AND HAS_DOCUMENT_DB_DEPENDENCY = true
    AND HAS_KEY_VALUE_DB_DEPENDENCY = false
    AND HAS_COLUMN_DB_DEPENDENCY = true
    AND HAS_GRAPH_DB_DEPENDENCY = true
) GROUP BY DATASET_VERSION;
--Key-Value DB & Column DB & Graph DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = false
    AND HAS_DOCUMENT_DB_DEPENDENCY = false
    AND HAS_KEY_VALUE_DB_DEPENDENCY = true
    AND HAS_COLUMN_DB_DEPENDENCY = true
    AND HAS_GRAPH_DB_DEPENDENCY = true
) GROUP BY DATASET_VERSION;

--Number of projects having four database types
--Relational DB & Document DB & Key-Value DB & Column DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = true
    AND HAS_DOCUMENT_DB_DEPENDENCY = true
    AND HAS_KEY_VALUE_DB_DEPENDENCY = true
    AND HAS_COLUMN_DB_DEPENDENCY = true
    AND HAS_GRAPH_DB_DEPENDENCY = false
) GROUP BY DATASET_VERSION;
--Relational DB & Document DB & Key-Value DB & Graph DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = true
    AND HAS_DOCUMENT_DB_DEPENDENCY = true
    AND HAS_KEY_VALUE_DB_DEPENDENCY = true
    AND HAS_COLUMN_DB_DEPENDENCY = false
    AND HAS_GRAPH_DB_DEPENDENCY = true
) GROUP BY DATASET_VERSION;
--Document DB & Key-Value DB & Column DB & Graph DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = false
    AND HAS_DOCUMENT_DB_DEPENDENCY = true
    AND HAS_KEY_VALUE_DB_DEPENDENCY = true
    AND HAS_COLUMN_DB_DEPENDENCY = true
    AND HAS_GRAPH_DB_DEPENDENCY = true
) GROUP BY DATASET_VERSION;
--Relational DB & Document DB & Column & Graph DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = true
    AND HAS_DOCUMENT_DB_DEPENDENCY = true
    AND HAS_KEY_VALUE_DB_DEPENDENCY = false
    AND HAS_COLUMN_DB_DEPENDENCY = true
    AND HAS_GRAPH_DB_DEPENDENCY = true
) GROUP BY DATASET_VERSION;
--Relational DB & Key-Value DB & Column & Graph DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = true
    AND HAS_DOCUMENT_DB_DEPENDENCY = false
    AND HAS_KEY_VALUE_DB_DEPENDENCY = true
    AND HAS_COLUMN_DB_DEPENDENCY = true
    AND HAS_GRAPH_DB_DEPENDENCY = true
) GROUP BY DATASET_VERSION;

--Number of projects having five database types
--Relational DB & Document DB & Key-Value DB & Column DB & Graph DB
SELECT COUNT(DISTINCT REPOSITORY_NAME), DATASET_VERSION FROM SQL_NOSQL_DISTINCT_REPOSITORY_DEPENDENCIES WHERE REPOSITORY_NAME IN (
    SELECT REPOSITORY_NAME
    FROM SQL_NOSQL_REPOSITORY_WITH_DBMS_TYPE
    WHERE HAS_RELATIONAL_DB_DEPENDENCY = true
    AND HAS_DOCUMENT_DB_DEPENDENCY = true
    AND HAS_KEY_VALUE_DB_DEPENDENCY = true
    AND HAS_COLUMN_DB_DEPENDENCY = true
    AND HAS_GRAPH_DB_DEPENDENCY = true
) GROUP BY DATASET_VERSION;